my first pull request
Yemisirach/Hello-world pull request #1
Opened 2022-11-29 15:23 UTC by Yemisirach

2022-11-29 16:43 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @Yemisirach, 
I'm Andres.

While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Great job following requirements. 💯 

## Required Changes ♻️

- [ ] You did great with using the GitHub flow! 💯 However, you could improve it even more if instead of naming your branch literally as `"Feature_1"` you use the actual name of the feature, in this case, a good name could be `"hello-microverse"`. ⚠️ **Do not try to change the name of this branch, instead, consider this tip for future projects!** ⚠️ 

- [ ] I noticed that you didn't install linters locally in your project, please consider following this [entire step-by-step tutorial](https://github.com/microverseinc/linters-config/tree/master/html-css) on how to add linters to your HTML and CSS projects. 🤓 🛠️ 

- [ ] Please consider adding a descriptive pull request summary and a title describing the changes you implemented, it is part of professional code documentation. 🤓 🛠️ 

![image](https://user-images.githubusercontent.com/77069011/204589784-b1c72569-5189-478c-8919-c88898bb7c10.png)



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 16:43 UTC, anagudelogu commented on test.md
> +"This file should be ignored by git"
- [ ] You did a great job following the requirements! 💯  However, please make sure that this file is ignored by git, in order to achieve this, you need to change your `.gitignore`: `./test.md` to just `test.md`. Consider fixing this one! 🤓 🛠️

2022-11-29 16:43 UTC, anagudelogu commented on .github/linters.yml
> +      - uses: actions/checkout@v2
- [ ] You did a great job setting up your linters on GitHub! 💯 However, in order for them to work they need to be inside another folder called `"workflows"`. Please consider following this [step-by-step tutorial](https://github.com/microverseinc/linters-config/tree/master/html-css) on how to set up linters for your HTML and CSS projects! 🤓 🛠️

2022-11-29 16:43 UTC, anagudelogu commented on README.md
> +practice learning about in professional rules on github repository
- [ ] Kindly use the [template provided by Microverse](https://github.com/microverseinc/readme-template) to document your code. Remember that having professional code documentation will make your projects more attractive to people that want to collaborate on them and also will provide better guidance on how to interact with them. Please consider using the template and customizing it with the project information! 🤓 🛠️

2022-11-30 08:23 UTC, Yemisirach commented
Add Microverse linters configuration and Add readme template as a professional code.

2022-11-30 08:48 UTC, levy002 requested changes
## Hello @Yemisirach    , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] As requested by the previous reviewer, kindly make sure to edit your PR description.

  _**Example of how you can edit your PR description**_
   ![chrome-capture-2022-10-30 (1)](https://user-images.githubusercontent.com/87197412/204739220-c02cf362-96b4-4215-9eaf-c82b1086a980.gif)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 08:48 UTC, levy002 commented on test.md
> +"This file should be ignored by git"
- [ ] As requested by the previous reviewer, kindly remove the `test.md` file because must not be presented in your repo as required (it must be ignored by git). :wink:

2022-11-30 16:43 UTC, Gopxfs approved these changes
# 🟢 STATUS: APPROVED 🟢

## Hello @Yemisirach 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 17:30 UTC, merged